# Generated by Django 5.2.4 on 2026-05-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
